version: '3.8'

networks:
  web:
    driver: bridge

services:
  db:
    image: library/postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - web
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  backend:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/app/
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=secret"
      - "DJANGO_DEBUG=1"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DJANGO_SU_NAME=admin"
      - "DJANGO_SU_EMAIL=''"
      - "DJANGO_SU_PASSWORD=admin"
    restart: "on-failure"
    networks:
      - web
volumes:
  postgres_data: