version: "3.9"

networks:
  web:
    driver: bridge

services:
  db:
    image: library/postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - web

  web:
    build:
      context: .
      dockerfile: "./Dockerfile"
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 8002:8000
    depends_on:
      - db
    restart: "on-failure"
    networks:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
