networks:
  web:
    driver: bridge

services:
  db:
    image: library/postgres:14.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - web

  backend:
    build:
      context: .
    env_file:
      - ./envs/.env
      - ./envs/.env.db
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: "on-failure"
    networks:
      - web

volumes:
  postgres_data:
  redisdata:
