# Generated by Django 4.0.1 on 2022-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(help_text='Language', max_length=200),
        ),
    ]
