# Generated by Django 4.0.1 on 2022-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.SmallIntegerField(),
        ),
    ]
