# Generated by Django 4.0.1 on 2022-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_language_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Authors list', related_name='authors', to='books.Author'),
        ),
    ]
