# Generated by Django 4.0.1 on 2022-01-30 10:52

import books.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_language_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Author name', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Authors list', related_name='authors', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.URLField(blank=True, help_text='Link to cover of the book', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN', max_length=13, null=True, validators=[books.validators.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Book language', on_delete=django.db.models.deletion.DO_NOTHING, to='books.language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Page count', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.SmallIntegerField(blank=True, help_text='Publish year', null=True, validators=[books.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(help_text='Language', max_length=200),
        ),
    ]
