version: "3.9"

networks:
  engine:
    driver: bridge

services:
  db:
    image: library/postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - engine

  web:
    build:
      context: .
      dockerfile: "./Dockerfile"
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 127.0.0.1:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: "on-failure"
    networks:
      - engine

volumes:
  postgres_data:
  static_volume:
  media_volume:
